from typing import Any, Literal

from pydantic import BaseModel, Field


class Message(BaseModel):
    """Represents a single turn in a conversation history.

    The model tracks conversation turns in a compact, serializable format so the
    same message history can be stored in a session log or sent to a retrieval
    layer for policy checks.
    """

    role: Literal["user", "assistant"]
    """The speaker of this conversation message."""

    content: str
    """The raw text content for the turn."""


class ToolCall(BaseModel):
    """Represents a tool invocation performed during a target evaluation run."""

    name: str
    """Tool name or capability being invoked."""

    arguments: dict[str, Any] = Field(default_factory=dict)
    """Structured arguments supplied to the tool."""

    result: str | None = None
    """Result text returned by the tool, if any."""


class TargetRequest(BaseModel):
    """Incoming request payload used by the service endpoint.

    This captures the complete conversation context, the execution mode, and the
    session identifier so the backend can evaluate the request in context.
    """

    conversation: list[Message]
    """Ordered chat history for the current evaluation request."""

    mode: Literal["rag", "agentic"]
    """Execution mode for the target service, either retrieval-based or agentic."""

    hardened: bool = False
    """Apply input filtering and retrieved-text sanitization when enabled."""

    session_id: str
    """Stable identifier for the user's session."""


class TargetResponse(BaseModel):
    """Structured response returned after a target evaluation has completed."""

    output: str
    """Primary response text or summary generated by the evaluator."""

    retrieved_doc_ids: list[str] = Field(default_factory=list)
    """Policy document references retrieved for the request."""

    retrieved_chunk_ids: list[str] = Field(default_factory=list)
    """Stable identifiers for retrieved chunks, in retrieval order."""

    retrieved_chunks: list[str] = Field(default_factory=list)
    """Relevant document chunks used during retrieval."""

    retrieval_ranks: dict[str, int] = Field(default_factory=dict)
    """Ranking metadata keyed by document ID."""

    tool_calls: list[ToolCall] = Field(default_factory=list)
    """Any tool calls made during the evaluation flow."""

    latency_ms: int = 0
    """Time spent during the evaluation in milliseconds."""

    usage: dict[str, Any] = Field(default_factory=dict)
    """Additional usage metadata such as token or cost information."""


class Attempt(BaseModel):
    """Represents a single mutated or tested attempt in a red-team workflow."""

    id: str
    """Unique attempt identifier."""

    category: str
    """Classification of the attack or evaluation type."""

    seed_id: str | None = None
    """Optional seed prompt or source that produced this attempt."""

    parent_attempt_id: str | None = None
    """Parent attempt used to derive this mutation, if applicable."""

    mutation_depth: int = 0
    """How deep the attempt is in a mutation tree or adversarial chain."""

    strategy_used: str
    """Strategy used to generate or alter the prompt or behavior."""

    conversation: list[Message]
    """Conversation content associated with this evaluation attempt."""

    expected_breach: list[str] = Field(default_factory=list)
    """Policies the attempt is expected to violate or trigger."""


class Verdict(BaseModel):
    """Outcome of a policy-evaluation pass against a candidate response."""

    attempt_id: str
    """Attempt identifier tied to this verdict."""

    judge_version: str
    """Version of the evaluation heuristic or judge used."""

    verdict: Literal[
        "breach",
        "defended",
        "not_delivered",
        "ambiguous"
    ]
    """Final classification for the evaluated output."""

    confidence: float
    """Confidence value assigned to the verdict."""

    policy_violated: list[str] = Field(default_factory=list)
    """List of policy categories triggered by the output."""

    evidence_span: str | None = None
    """Short span of text used as justification for the verdict."""

    severity: Literal[
        "critical",
        "high",
        "medium",
        "low"
    ] | None = None
    """Severity level associated with the policy violation."""

    reasoning: str
    """Human-readable explanation of why the verdict was assigned."""